name: Continuous Integration - Develop Environment

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: deploy
        ports:
          - 3306:3306
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build and test
        env:
          MYSQL_DATABASE: ${{env.MYSQL_DATABASE}}
          MYSQL_HOST: ${{env.MYSQL_HOST}}
          MYSQL_PASSWORD: ${{env.MYSQL_PASSWORD}}
          MYSQL_PORT: ${{env.MYSQL_PORT}}
          MYSQL_USER: ${{env.MYSQL_USER}}
          MONGODB_HOST: ${{env.MONGODB_HOST}}
          MONGODB_PORT: ${{env.MONGODB_PORT}}
          MONGODB_DATABASE: ${{env.MONGODB_DATABASE}}
        run: ./gradlew test
