name: Continuous Integration - Develop Environment
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
        
      - name: Build and test
        run: ./gradlew test
